package renderer

import "io"

// TemplateRenderer is the interface for rendering compiled templates.
// It is defined in a public package so that code generated by hbc -bootstrap
// (in user modules) can reference it without importing internal packages.
type TemplateRenderer interface {
	Render(templateName string, w io.Writer, data any) error
}
