// Code generated by hbc; DO NOT EDIT.
// Compiler version: 0.1.2
package showcase

import (
	handlebars "github.com/andriyg76/go-hbars/helpers/handlebars"
	runtime "github.com/andriyg76/go-hbars/runtime"
	"io"
	"strings"
)

// Template inclusion (who includes whom):
// ```mermaid
// flowchart LR
// main --> footer
// main --> header
// ```
//
// Context type structure:
// ```mermaid
// classDiagram
// MainContext --> MainFooterContext : Footer()
// MainContext --> MainHeaderContext : Header()
// class OrderRowContext { }
// class UserCardContext { }
// ```

// from examples/showcase/templates/main.hbs:1

// MainContext is the context interface inferred from template "main".
type MainContext interface {
	Footer() MainFooterContext
	Header() MainHeaderContext
	Orders() any
	RawHtml() any
	Settings() MainSettingsContext
	Site() MainSiteContext
	User() MainUserContext
	Raw() any
}

// MainUserContext is the context for path "user".
type MainUserContext interface {
	Bio() any
	Email() any
	Joined() any
	Name() any
	Profile() MainUserProfileContext
	Role() any
	Tags() any
	Raw() any
}

// MainUserProfileContext is the context for path "user.profile".
type MainUserProfileContext interface {
	Note() any
	Title() any
	Raw() any
}

// MainFooterContext is the context for path "footer".
type MainFooterContext interface {
	Stats() MainFooterStatsContext
	Users() any
	Raw() any
}

// MainFooterStatsContext is the context for path "footer.stats".
type MainFooterStatsContext interface {
	Avg() any
	Total() any
	Raw() any
}

// MainHeaderContext is the context for path "header".
type MainHeaderContext interface {
	Site() MainHeaderSiteContext
	Raw() any
}

// MainHeaderSiteContext is the context for path "header.site".
type MainHeaderSiteContext interface {
	Title() any
	Url() any
	Raw() any
}

// MainSiteContext is the context for path "site".
type MainSiteContext interface {
	Title() any
	Url() any
	Raw() any
}

// MainSettingsContext is the context for path "settings".
type MainSettingsContext interface {
	FeatureFlags() any
	Raw() any
}

// from examples/showcase/templates/orderRow.hbs:1

// OrderRowContext is the context interface inferred from template "orderRow".
type OrderRowContext interface {
	Id() any
	Items() any
	Subtotal() any
	Tax() any
	Raw() any
}

// from examples/showcase/templates/userCard.hbs:1

// UserCardContext is the context interface inferred from template "userCard".
type UserCardContext interface {
	Active() any
	Email() any
	Name() any
	Role() any
	Score() any
	Raw() any
}

// from examples/showcase/templates/main.hbs:1

// MainFooterStatsContextData is a map-backed implementation of MainFooterStatsContext.
type MainFooterStatsContextData struct{ m map[string]any }

func (d MainFooterStatsContextData) Avg() any   { return d.m["avg"] }
func (d MainFooterStatsContextData) Total() any { return d.m["total"] }
func (d MainFooterStatsContextData) Raw() any   { return d.m }

// MainFooterStatsContextFromMap returns a MainFooterStatsContext backed by m. If m is nil, a new empty map is used.
func MainFooterStatsContextFromMap(m map[string]any) MainFooterStatsContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainFooterStatsContextData{m}
}

// MainFooterContextData is a map-backed implementation of MainFooterContext.
type MainFooterContextData struct{ m map[string]any }

func (d MainFooterContextData) Stats() MainFooterStatsContext {
	v := d.m["stats"]
	if v == nil {
		return MainFooterStatsContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainFooterStatsContextData{map[string]any{}}
	}
	return MainFooterStatsContextData{m}
}
func (d MainFooterContextData) Users() any { return d.m["users"] }
func (d MainFooterContextData) Raw() any   { return d.m }

// MainFooterContextFromMap returns a MainFooterContext backed by m. If m is nil, a new empty map is used.
func MainFooterContextFromMap(m map[string]any) MainFooterContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainFooterContextData{m}
}

// MainHeaderSiteContextData is a map-backed implementation of MainHeaderSiteContext.
type MainHeaderSiteContextData struct{ m map[string]any }

func (d MainHeaderSiteContextData) Title() any { return d.m["title"] }
func (d MainHeaderSiteContextData) Url() any   { return d.m["url"] }
func (d MainHeaderSiteContextData) Raw() any   { return d.m }

// MainHeaderSiteContextFromMap returns a MainHeaderSiteContext backed by m. If m is nil, a new empty map is used.
func MainHeaderSiteContextFromMap(m map[string]any) MainHeaderSiteContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainHeaderSiteContextData{m}
}

// MainHeaderContextData is a map-backed implementation of MainHeaderContext.
type MainHeaderContextData struct{ m map[string]any }

func (d MainHeaderContextData) Site() MainHeaderSiteContext {
	v := d.m["site"]
	if v == nil {
		return MainHeaderSiteContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainHeaderSiteContextData{map[string]any{}}
	}
	return MainHeaderSiteContextData{m}
}
func (d MainHeaderContextData) Raw() any { return d.m }

// MainHeaderContextFromMap returns a MainHeaderContext backed by m. If m is nil, a new empty map is used.
func MainHeaderContextFromMap(m map[string]any) MainHeaderContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainHeaderContextData{m}
}

// MainSettingsContextData is a map-backed implementation of MainSettingsContext.
type MainSettingsContextData struct{ m map[string]any }

func (d MainSettingsContextData) FeatureFlags() any { return d.m["featureFlags"] }
func (d MainSettingsContextData) Raw() any          { return d.m }

// MainSettingsContextFromMap returns a MainSettingsContext backed by m. If m is nil, a new empty map is used.
func MainSettingsContextFromMap(m map[string]any) MainSettingsContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainSettingsContextData{m}
}

// MainSiteContextData is a map-backed implementation of MainSiteContext.
type MainSiteContextData struct{ m map[string]any }

func (d MainSiteContextData) Title() any { return d.m["title"] }
func (d MainSiteContextData) Url() any   { return d.m["url"] }
func (d MainSiteContextData) Raw() any   { return d.m }

// MainSiteContextFromMap returns a MainSiteContext backed by m. If m is nil, a new empty map is used.
func MainSiteContextFromMap(m map[string]any) MainSiteContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainSiteContextData{m}
}

// MainUserProfileContextData is a map-backed implementation of MainUserProfileContext.
type MainUserProfileContextData struct{ m map[string]any }

func (d MainUserProfileContextData) Note() any  { return d.m["note"] }
func (d MainUserProfileContextData) Title() any { return d.m["title"] }
func (d MainUserProfileContextData) Raw() any   { return d.m }

// MainUserProfileContextFromMap returns a MainUserProfileContext backed by m. If m is nil, a new empty map is used.
func MainUserProfileContextFromMap(m map[string]any) MainUserProfileContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainUserProfileContextData{m}
}

// MainUserContextData is a map-backed implementation of MainUserContext.
type MainUserContextData struct{ m map[string]any }

func (d MainUserContextData) Bio() any    { return d.m["bio"] }
func (d MainUserContextData) Email() any  { return d.m["email"] }
func (d MainUserContextData) Joined() any { return d.m["joined"] }
func (d MainUserContextData) Name() any   { return d.m["name"] }
func (d MainUserContextData) Profile() MainUserProfileContext {
	v := d.m["profile"]
	if v == nil {
		return MainUserProfileContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainUserProfileContextData{map[string]any{}}
	}
	return MainUserProfileContextData{m}
}
func (d MainUserContextData) Role() any { return d.m["role"] }
func (d MainUserContextData) Tags() any { return d.m["tags"] }
func (d MainUserContextData) Raw() any  { return d.m }

// MainUserContextFromMap returns a MainUserContext backed by m. If m is nil, a new empty map is used.
func MainUserContextFromMap(m map[string]any) MainUserContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainUserContextData{m}
}

// MainContextData is a map-backed implementation of MainContext.
type MainContextData struct{ m map[string]any }

func (d MainContextData) Footer() MainFooterContext {
	v := d.m["footer"]
	if v == nil {
		return MainFooterContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainFooterContextData{map[string]any{}}
	}
	return MainFooterContextData{m}
}
func (d MainContextData) Header() MainHeaderContext {
	v := d.m["header"]
	if v == nil {
		return MainHeaderContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainHeaderContextData{map[string]any{}}
	}
	return MainHeaderContextData{m}
}
func (d MainContextData) Orders() any  { return d.m["orders"] }
func (d MainContextData) RawHtml() any { return d.m["rawHtml"] }
func (d MainContextData) Settings() MainSettingsContext {
	v := d.m["settings"]
	if v == nil {
		return MainSettingsContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainSettingsContextData{map[string]any{}}
	}
	return MainSettingsContextData{m}
}
func (d MainContextData) Site() MainSiteContext {
	v := d.m["site"]
	if v == nil {
		return MainSiteContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainSiteContextData{map[string]any{}}
	}
	return MainSiteContextData{m}
}
func (d MainContextData) User() MainUserContext {
	v := d.m["user"]
	if v == nil {
		return MainUserContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainUserContextData{map[string]any{}}
	}
	return MainUserContextData{m}
}
func (d MainContextData) Raw() any { return d.m }

// MainContextFromMap returns a MainContext backed by m. If m is nil, a new empty map is used.
func MainContextFromMap(m map[string]any) MainContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainContextData{m}
}

// from examples/showcase/templates/orderRow.hbs:1

// OrderRowContextData is a map-backed implementation of OrderRowContext.
type OrderRowContextData struct{ m map[string]any }

func (d OrderRowContextData) Id() any       { return d.m["id"] }
func (d OrderRowContextData) Items() any    { return d.m["items"] }
func (d OrderRowContextData) Subtotal() any { return d.m["subtotal"] }
func (d OrderRowContextData) Tax() any      { return d.m["tax"] }
func (d OrderRowContextData) Raw() any      { return d.m }

// OrderRowContextFromMap returns a OrderRowContext backed by m. If m is nil, a new empty map is used.
func OrderRowContextFromMap(m map[string]any) OrderRowContext {
	if m == nil {
		m = make(map[string]any)
	}
	return OrderRowContextData{m}
}

// from examples/showcase/templates/userCard.hbs:1

// UserCardContextData is a map-backed implementation of UserCardContext.
type UserCardContextData struct{ m map[string]any }

func (d UserCardContextData) Active() any { return d.m["active"] }
func (d UserCardContextData) Email() any  { return d.m["email"] }
func (d UserCardContextData) Name() any   { return d.m["name"] }
func (d UserCardContextData) Role() any   { return d.m["role"] }
func (d UserCardContextData) Score() any  { return d.m["score"] }
func (d UserCardContextData) Raw() any    { return d.m }

// UserCardContextFromMap returns a UserCardContext backed by m. If m is nil, a new empty map is used.
func UserCardContextFromMap(m map[string]any) UserCardContext {
	if m == nil {
		m = make(map[string]any)
	}
	return UserCardContextData{m}
}

var partials map[string]func(any, io.Writer, any) error

// contextMap returns map[string]any from ctx (either direct map or Raw() from context data).
func contextMap(ctx any) map[string]any {
	if m, ok := ctx.(map[string]any); ok {
		return m
	}
	type rawer interface{ Raw() any }
	if r, ok := ctx.(rawer); ok {
		if m, ok := r.Raw().(map[string]any); ok {
			return m
		}
	}
	return nil
}

func init() {
	partials = map[string]func(any, io.Writer, any) error{
		"footer": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderFooter(MainContextFromMap(m), w, MainContextFromMap(m))
		},
		"header": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderHeader(MainContextFromMap(m), w, MainContextFromMap(m))
		},
		"main": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderMain(MainContextFromMap(m), w, MainContextFromMap(m))
		},
		"orderRow": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderOrderRow(OrderRowContextFromMap(m), w, OrderRowContextFromMap(m))
		},
		"userCard": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderUserCard(UserCardContextFromMap(m), w, UserCardContextFromMap(m))
		},
	}
}

// from examples/showcase/templates/footer.hbs:1
func renderFooter(data MainContext, w io.Writer, root MainContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<footer>\n  Total: "); err != nil {
		return err
	}
	result1, err := handlebars.FormatNumber(runtime.HelperArgs{
		Args: []any{
			nil,
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result1); err != nil {
		return err
	}
	if _, err := io.WriteString(w, " (avg "); err != nil {
		return err
	}
	result2, err := handlebars.FormatNumber(runtime.HelperArgs{
		Args: []any{
			nil,
		},
		HashArgs: runtime.Hash{
			"precision": int64(2),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result2); err != nil {
		return err
	}
	if _, err := io.WriteString(w, ")\n  Users: "); err != nil {
		return err
	}
	result3, err := handlebars.Length(runtime.HelperArgs{
		Args: []any{
			nil,
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result3); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n</footer>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderFooter(w io.Writer, data MainContext) error {
	return renderFooter(data, w, data)
}

func RenderFooterString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderFooter(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// from examples/showcase/templates/header.hbs:1
func renderHeader(data MainContext, w io.Writer, root MainContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<header>\n  <h1>"); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Site().Title()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</h1>\n  <p>"); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Site().Url()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n  <p>Generated: "); err != nil {
		return err
	}
	result1, err := handlebars.Now(runtime.HelperArgs{
		Args: nil,
		HashArgs: runtime.Hash{
			"format": "2006-01-02T15:04:05Z07:00",
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result1); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n</header>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderHeader(w io.Writer, data MainContext) error {
	return renderHeader(data, w, data)
}

func RenderHeaderString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderHeader(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// from examples/showcase/templates/main.hbs:1
func renderMain(data MainContext, w io.Writer, root MainContext) error {
	if data == nil {
		return nil
	}
	if err := renderHeader(data, w, data); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\nSite: "); err != nil {
		return err
	}
	result1, err := handlebars.Upper(runtime.HelperArgs{
		Args: []any{
			data.Site().Title(),
		},
	})
	if err != nil {
		return err
	}
	result2, err := handlebars.Replace(runtime.HelperArgs{
		Args: []any{
			result1,
			" ",
			"-",
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result2); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\nURL: "); err != nil {
		return err
	}
	result3, err := handlebars.StripProtocol(runtime.HelperArgs{
		Args: []any{
			data.Site().Url(),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result3); err != nil {
		return err
	}
	if _, err := io.WriteString(w, " (clean: "); err != nil {
		return err
	}
	result4, err := handlebars.StripQuerystring(runtime.HelperArgs{
		Args: []any{
			data.Site().Url(),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result4); err != nil {
		return err
	}
	if _, err := io.WriteString(w, ")\nFlags ("); err != nil {
		return err
	}
	result5, err := handlebars.Size(runtime.HelperArgs{
		Args: []any{
			data.Settings().FeatureFlags(),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result5); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "): "); err != nil {
		return err
	}
	result6, err := handlebars.Keys(runtime.HelperArgs{
		Args: []any{
			data.Settings().FeatureFlags(),
		},
	})
	if err != nil {
		return err
	}
	result7, err := handlebars.Join(runtime.HelperArgs{
		Args: []any{
			result6,
		},
		HashArgs: runtime.Hash{
			"separator": ", ",
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result7); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\nFlag values: "); err != nil {
		return err
	}
	result8, err := handlebars.Values(runtime.HelperArgs{
		Args: []any{
			data.Settings().FeatureFlags(),
		},
	})
	if err != nil {
		return err
	}
	result9, err := handlebars.Join(runtime.HelperArgs{
		Args: []any{
			result8,
		},
		HashArgs: runtime.Hash{
			"separator": ", ",
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result9); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n"); err != nil {
		return err
	}
	ctx10 := data.User()
	cond11, err12 := runtime.IsTruthy(ctx10)
	if err12 != nil {
		return err12
	}
	if cond11 {
		if _, err := io.WriteString(w, "\nName: "); err != nil {
			return err
		}
		result13, err := handlebars.Capitalize(runtime.HelperArgs{
			Args: []any{
				ctx10.Name(),
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result13); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nEmail: "); err != nil {
			return err
		}
		result14, err := handlebars.Lower(runtime.HelperArgs{
			Args: []any{
				ctx10.Email(),
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result14); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nRole: "); err != nil {
			return err
		}
		result15, err := handlebars.Upper(runtime.HelperArgs{
			Args: []any{
				ctx10.Role(),
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result15); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nJoined: "); err != nil {
			return err
		}
		result16, err := handlebars.FormatDate(runtime.HelperArgs{
			Args: []any{
				ctx10.Joined(),
			},
			HashArgs: runtime.Hash{
				"format": "2006-01-02",
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result16); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nBio: "); err != nil {
			return err
		}
		result17, err := handlebars.Truncate(runtime.HelperArgs{
			Args: []any{
				ctx10.Bio(),
			},
			HashArgs: runtime.Hash{
				"length": int64(60),
				"suffix": "...",
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteRaw(w, result17); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nStatus: "); err != nil {
			return err
		}
		result18, err := handlebars.Gt(runtime.HelperArgs{
			Args: []any{
				nil,
				int64(80),
			},
		})
		if err != nil {
			return err
		}
		result19, err := handlebars.And(runtime.HelperArgs{
			Args: []any{
				nil,
				result18,
			},
		})
		if err != nil {
			return err
		}
		val20 := result19
		cond21, err22 := runtime.IsTruthy(val20)
		if err22 != nil {
			return err22
		}
		if cond21 {
			if _, err := io.WriteString(w, "VIP"); err != nil {
				return err
			}
		} else {
			if _, err := io.WriteString(w, "Standard"); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, "\nTags: "); err != nil {
			return err
		}
		result23, err := handlebars.Join(runtime.HelperArgs{
			Args: []any{
				ctx10.Tags(),
			},
			HashArgs: runtime.Hash{
				"separator": ", ",
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result23); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nProfile: "); err != nil {
			return err
		}
		result24, err := handlebars.Default(runtime.HelperArgs{
			Args: []any{
				ctx10.Profile().Title(),
				"n/a",
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result24); err != nil {
			return err
		}
		if _, err := io.WriteString(w, " / "); err != nil {
			return err
		}
		result25, err := handlebars.Default(runtime.HelperArgs{
			Args: []any{
				ctx10.Profile().Note(),
				"n/a",
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result25); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nEmail parts: "); err != nil {
			return err
		}
		result26, err := handlebars.Split(runtime.HelperArgs{
			Args: []any{
				ctx10.Email(),
				"@",
			},
		})
		if err != nil {
			return err
		}
		result27, err := handlebars.Join(runtime.HelperArgs{
			Args: []any{
				result26,
			},
			HashArgs: runtime.Hash{
				"separator": "@",
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result27); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\n"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n\nOrders:\n"); err != nil {
		return err
	}
	items30 := data.Orders()
	sl31, _eachSliceOk := items30.([]any)
	if _eachSliceOk && len(sl31) > 0 {
		for key29, item28 := range sl31 {
			_, _ = key29, item28
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
			partialBase33 := item28
			if err := partials["orderRow"](partialBase33, w, partialBase33); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nOrder index "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, key29); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " first="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " last="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nParent site: "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, data.Site().Title()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nRoot year: "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, runtime.LookupPath(root, "site.year")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
		}
	} else if m32, _eachMapOk := items30.(map[string]any); _eachMapOk && len(m32) > 0 {
		for key29, item28 := range m32 {
			_, _ = key29, item28
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
			partialBase34 := item28
			if err := partials["orderRow"](partialBase34, w, partialBase34); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nOrder index "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, key29); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " first="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " last="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nParent site: "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, data.Site().Title()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nRoot year: "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, runtime.LookupPath(root, "site.year")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
		}
	}
	if _, err := io.WriteString(w, "\n\nRaw HTML stripped: "); err != nil {
		return err
	}
	result35, err := handlebars.StripTags(runtime.HelperArgs{
		Args: []any{
			data.RawHtml(),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result35); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\nDynamic card:\n"); err != nil {
		return err
	}
	partialBase36 := data.User()
	result37, err := handlebars.Lookup(runtime.HelperArgs{
		Args: []any{
			data,
			"cardPartial",
		},
	})
	if err != nil {
		return err
	}
	partial38 := runtime.Stringify(result37)
	partialFn, ok := partials[partial38]
	if !ok {
		runtime.MissingPartialOutput(w, partial38)
	} else if err := partialFn(partialBase36, w, partialBase36); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n"); err != nil {
		return err
	}
	if err := renderFooter(data, w, data); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderMain(w io.Writer, data MainContext) error {
	return renderMain(data, w, data)
}

func RenderMainString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderMain(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// from examples/showcase/templates/orderRow.hbs:1
func renderOrderRow(data OrderRowContext, w io.Writer, root OrderRowContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<div class=\"order\">\n  <span>Order #"); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Id()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Items: "); err != nil {
		return err
	}
	result1, err := handlebars.Length(runtime.HelperArgs{
		Args: []any{
			data.Items(),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result1); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Subtotal: "); err != nil {
		return err
	}
	result2, err := handlebars.FormatNumber(runtime.HelperArgs{
		Args: []any{
			data.Subtotal(),
		},
		HashArgs: runtime.Hash{
			"precision": int64(2),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result2); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Tax: "); err != nil {
		return err
	}
	result3, err := handlebars.FormatNumber(runtime.HelperArgs{
		Args: []any{
			data.Tax(),
		},
		HashArgs: runtime.Hash{
			"precision": int64(2),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result3); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Total: "); err != nil {
		return err
	}
	result4, err := handlebars.Add(runtime.HelperArgs{
		Args: []any{
			data.Subtotal(),
			data.Tax(),
		},
	})
	if err != nil {
		return err
	}
	result5, err := handlebars.FormatNumber(runtime.HelperArgs{
		Args: []any{
			result4,
		},
		HashArgs: runtime.Hash{
			"precision": int64(2),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result5); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>First: "); err != nil {
		return err
	}
	result6, err := handlebars.First(runtime.HelperArgs{
		Args: []any{
			data.Items(),
		},
	})
	if err != nil {
		return err
	}
	result7, err := handlebars.Default(runtime.HelperArgs{
		Args: []any{
			result6,
			"n/a",
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result7); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Last: "); err != nil {
		return err
	}
	result8, err := handlebars.Last(runtime.HelperArgs{
		Args: []any{
			data.Items(),
		},
	})
	if err != nil {
		return err
	}
	result9, err := handlebars.Default(runtime.HelperArgs{
		Args: []any{
			result8,
			"n/a",
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result9); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n</div>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderOrderRow(w io.Writer, data OrderRowContext) error {
	return renderOrderRow(data, w, data)
}

func RenderOrderRowString(data OrderRowContext) (string, error) {
	var b strings.Builder
	if err := RenderOrderRow(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// from examples/showcase/templates/userCard.hbs:1
func renderUserCard(data UserCardContext, w io.Writer, root UserCardContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<div class=\"user-card\">\n  <h2>"); err != nil {
		return err
	}
	result1, err := handlebars.Capitalize(runtime.HelperArgs{
		Args: []any{
			data.Name(),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result1); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</h2>\n  <p>"); err != nil {
		return err
	}
	result2, err := handlebars.Lower(runtime.HelperArgs{
		Args: []any{
			data.Email(),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result2); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n  <p>Role: "); err != nil {
		return err
	}
	result3, err := handlebars.Upper(runtime.HelperArgs{
		Args: []any{
			data.Role(),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result3); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n  "); err != nil {
		return err
	}
	result4, err := handlebars.Eq(runtime.HelperArgs{
		Args: []any{
			data.Role(),
			"admin",
		},
	})
	if err != nil {
		return err
	}
	val5 := result4
	cond6, err7 := runtime.IsTruthy(val5)
	if err7 != nil {
		return err7
	}
	if cond6 {
		if _, err := io.WriteString(w, "<strong>Admin</strong>"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n  "); err != nil {
		return err
	}
	val8 := data.Active()
	cond9, err10 := runtime.IsTruthy(val8)
	if err10 != nil {
		return err10
	}
	if !cond9 {
		if _, err := io.WriteString(w, "<em>Inactive</em>"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n  <p>Score: "); err != nil {
		return err
	}
	result11, err := handlebars.ToFixed(runtime.HelperArgs{
		Args: []any{
			data.Score(),
			int64(1),
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result11); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n</div>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderUserCard(w io.Writer, data UserCardContext) error {
	return renderUserCard(data, w, data)
}

func RenderUserCardString(data UserCardContext) (string, error) {
	var b strings.Builder
	if err := RenderUserCard(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}
