// Code generated by hbc; DO NOT EDIT.
package showcase

import (
	handlebars "github.com/andriyg76/go-hbars/helpers/handlebars"
	runtime "github.com/andriyg76/go-hbars/runtime"
	"io"
	"strings"
)

// MainContext is the context interface inferred from template "main".
type MainContext interface {
	Id() any
	Items() any
	Orders() any
	RawHtml() any
	Settings() MainSettingsContext
	Site() MainSiteContext
	Stats() MainStatsContext
	Subtotal() any
	Tax() any
	User() MainUserContext
	Users() any
	Raw() any
}

// MainSettingsContext is the context for path "settings".
type MainSettingsContext interface {
	FeatureFlags() any
	Raw() any
}

// MainUserContext is the context for path "user".
type MainUserContext interface {
	Bio() any
	Email() any
	Joined() any
	Name() any
	Profile() MainUserProfileContext
	Role() any
	Tags() any
	Raw() any
}

// MainUserProfileContext is the context for path "user.profile".
type MainUserProfileContext interface {
	Note() any
	Title() any
	Raw() any
}

// MainSiteContext is the context for path "site".
type MainSiteContext interface {
	Title() any
	Url() any
	Raw() any
}

// MainStatsContext is the context for path "stats".
type MainStatsContext interface {
	Avg() any
	Total() any
	Raw() any
}

// OrderRowContext is the context interface inferred from template "orderRow".
type OrderRowContext interface {
	Id() any
	Items() any
	Subtotal() any
	Tax() any
	Raw() any
}

// UserCardContext is the context interface inferred from template "userCard".
type UserCardContext interface {
	Active() any
	Email() any
	Name() any
	Role() any
	Score() any
	Raw() any
}

// MainSettingsContextData is a map-backed implementation of MainSettingsContext.
type MainSettingsContextData struct{ m map[string]any }

func (d MainSettingsContextData) FeatureFlags() any { return d.m["featureFlags"] }
func (d MainSettingsContextData) Raw() any          { return d.m }

// MainSettingsContextFromMap returns a MainSettingsContext backed by m. If m is nil, a new empty map is used.
func MainSettingsContextFromMap(m map[string]any) MainSettingsContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainSettingsContextData{m}
}

// MainSiteContextData is a map-backed implementation of MainSiteContext.
type MainSiteContextData struct{ m map[string]any }

func (d MainSiteContextData) Title() any { return d.m["title"] }
func (d MainSiteContextData) Url() any   { return d.m["url"] }
func (d MainSiteContextData) Raw() any   { return d.m }

// MainSiteContextFromMap returns a MainSiteContext backed by m. If m is nil, a new empty map is used.
func MainSiteContextFromMap(m map[string]any) MainSiteContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainSiteContextData{m}
}

// MainStatsContextData is a map-backed implementation of MainStatsContext.
type MainStatsContextData struct{ m map[string]any }

func (d MainStatsContextData) Avg() any   { return d.m["avg"] }
func (d MainStatsContextData) Total() any { return d.m["total"] }
func (d MainStatsContextData) Raw() any   { return d.m }

// MainStatsContextFromMap returns a MainStatsContext backed by m. If m is nil, a new empty map is used.
func MainStatsContextFromMap(m map[string]any) MainStatsContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainStatsContextData{m}
}

// MainUserProfileContextData is a map-backed implementation of MainUserProfileContext.
type MainUserProfileContextData struct{ m map[string]any }

func (d MainUserProfileContextData) Note() any  { return d.m["note"] }
func (d MainUserProfileContextData) Title() any { return d.m["title"] }
func (d MainUserProfileContextData) Raw() any   { return d.m }

// MainUserProfileContextFromMap returns a MainUserProfileContext backed by m. If m is nil, a new empty map is used.
func MainUserProfileContextFromMap(m map[string]any) MainUserProfileContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainUserProfileContextData{m}
}

// MainUserContextData is a map-backed implementation of MainUserContext.
type MainUserContextData struct{ m map[string]any }

func (d MainUserContextData) Bio() any    { return d.m["bio"] }
func (d MainUserContextData) Email() any  { return d.m["email"] }
func (d MainUserContextData) Joined() any { return d.m["joined"] }
func (d MainUserContextData) Name() any   { return d.m["name"] }
func (d MainUserContextData) Profile() MainUserProfileContext {
	v := d.m["profile"]
	if v == nil {
		return MainUserProfileContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainUserProfileContextData{map[string]any{}}
	}
	return MainUserProfileContextData{m}
}
func (d MainUserContextData) Role() any { return d.m["role"] }
func (d MainUserContextData) Tags() any { return d.m["tags"] }
func (d MainUserContextData) Raw() any  { return d.m }

// MainUserContextFromMap returns a MainUserContext backed by m. If m is nil, a new empty map is used.
func MainUserContextFromMap(m map[string]any) MainUserContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainUserContextData{m}
}

// MainContextData is a map-backed implementation of MainContext.
type MainContextData struct{ m map[string]any }

func (d MainContextData) Id() any      { return d.m["id"] }
func (d MainContextData) Items() any   { return d.m["items"] }
func (d MainContextData) Orders() any  { return d.m["orders"] }
func (d MainContextData) RawHtml() any { return d.m["rawHtml"] }
func (d MainContextData) Settings() MainSettingsContext {
	v := d.m["settings"]
	if v == nil {
		return MainSettingsContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainSettingsContextData{map[string]any{}}
	}
	return MainSettingsContextData{m}
}
func (d MainContextData) Site() MainSiteContext {
	v := d.m["site"]
	if v == nil {
		return MainSiteContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainSiteContextData{map[string]any{}}
	}
	return MainSiteContextData{m}
}
func (d MainContextData) Stats() MainStatsContext {
	v := d.m["stats"]
	if v == nil {
		return MainStatsContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainStatsContextData{map[string]any{}}
	}
	return MainStatsContextData{m}
}
func (d MainContextData) Subtotal() any { return d.m["subtotal"] }
func (d MainContextData) Tax() any      { return d.m["tax"] }
func (d MainContextData) User() MainUserContext {
	v := d.m["user"]
	if v == nil {
		return MainUserContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainUserContextData{map[string]any{}}
	}
	return MainUserContextData{m}
}
func (d MainContextData) Users() any { return d.m["users"] }
func (d MainContextData) Raw() any   { return d.m }

// MainContextFromMap returns a MainContext backed by m. If m is nil, a new empty map is used.
func MainContextFromMap(m map[string]any) MainContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainContextData{m}
}

// OrderRowContextData is a map-backed implementation of OrderRowContext.
type OrderRowContextData struct{ m map[string]any }

func (d OrderRowContextData) Id() any       { return d.m["id"] }
func (d OrderRowContextData) Items() any    { return d.m["items"] }
func (d OrderRowContextData) Subtotal() any { return d.m["subtotal"] }
func (d OrderRowContextData) Tax() any      { return d.m["tax"] }
func (d OrderRowContextData) Raw() any      { return d.m }

// OrderRowContextFromMap returns a OrderRowContext backed by m. If m is nil, a new empty map is used.
func OrderRowContextFromMap(m map[string]any) OrderRowContext {
	if m == nil {
		m = make(map[string]any)
	}
	return OrderRowContextData{m}
}

// UserCardContextData is a map-backed implementation of UserCardContext.
type UserCardContextData struct{ m map[string]any }

func (d UserCardContextData) Active() any { return d.m["active"] }
func (d UserCardContextData) Email() any  { return d.m["email"] }
func (d UserCardContextData) Name() any   { return d.m["name"] }
func (d UserCardContextData) Role() any   { return d.m["role"] }
func (d UserCardContextData) Score() any  { return d.m["score"] }
func (d UserCardContextData) Raw() any    { return d.m }

// UserCardContextFromMap returns a UserCardContext backed by m. If m is nil, a new empty map is used.
func UserCardContextFromMap(m map[string]any) UserCardContext {
	if m == nil {
		m = make(map[string]any)
	}
	return UserCardContextData{m}
}

var partials map[string]func(any, io.Writer) error

// contextMap returns map[string]any from ctx (either direct map or Raw() from context data).
func contextMap(ctx any) map[string]any {
	if m, ok := ctx.(map[string]any); ok {
		return m
	}
	type rawer interface{ Raw() any }
	if r, ok := ctx.(rawer); ok {
		if m, ok := r.Raw().(map[string]any); ok {
			return m
		}
	}
	return nil
}

func init() {
	partials = map[string]func(any, io.Writer) error{
		"footer": func(ctx any, w io.Writer) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderFooter(MainContextFromMap(m), w)
		},
		"header": func(ctx any, w io.Writer) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderHeader(MainContextFromMap(m), w)
		},
		"main": func(ctx any, w io.Writer) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderMain(MainContextFromMap(m), w)
		},
		"orderRow": func(ctx any, w io.Writer) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderOrderRow(OrderRowContextFromMap(m), w)
		},
		"userCard": func(ctx any, w io.Writer) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderUserCard(UserCardContextFromMap(m), w)
		},
	}
}

func renderFooter(data MainContext, w io.Writer) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<footer>\n  Total: "); err != nil {
		return err
	}
	args1 := []any{
		data.Stats().Total(),
	}
	result2, err := handlebars.FormatNumber(args1)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result2); err != nil {
		return err
	}
	if _, err := io.WriteString(w, " (avg "); err != nil {
		return err
	}
	hash3 := runtime.Hash{
		"precision": int64(2),
	}
	args4 := []any{
		data.Stats().Avg(),
		hash3,
	}
	result5, err := handlebars.FormatNumber(args4)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result5); err != nil {
		return err
	}
	if _, err := io.WriteString(w, ")\n  Users: "); err != nil {
		return err
	}
	args6 := []any{
		data.Users(),
	}
	result7, err := handlebars.Length(args6)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result7); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n</footer>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderFooter(w io.Writer, data MainContext) error {
	return renderFooter(data, w)
}

func RenderFooterString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderFooter(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

func renderHeader(data MainContext, w io.Writer) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<header>\n  <h1>"); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Site().Title()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</h1>\n  <p>"); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Site().Url()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n  <p>Generated: "); err != nil {
		return err
	}
	hash1 := runtime.Hash{
		"format": "2006-01-02T15:04:05Z07:00",
	}
	args2 := []any{
		hash1,
	}
	result3, err := handlebars.Now(args2)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result3); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n</header>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderHeader(w io.Writer, data MainContext) error {
	return renderHeader(data, w)
}

func RenderHeaderString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderHeader(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

func renderMain(data MainContext, w io.Writer) error {
	if data == nil {
		return nil
	}
	if err := renderHeader(data, w); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\nSite: "); err != nil {
		return err
	}
	args1 := []any{
		data.Site().Title(),
	}
	result2, err := handlebars.Upper(args1)
	if err != nil {
		return err
	}
	args3 := []any{
		result2,
		" ",
		"-",
	}
	result4, err := handlebars.Replace(args3)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result4); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\nURL: "); err != nil {
		return err
	}
	args5 := []any{
		data.Site().Url(),
	}
	result6, err := handlebars.StripProtocol(args5)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result6); err != nil {
		return err
	}
	if _, err := io.WriteString(w, " (clean: "); err != nil {
		return err
	}
	args7 := []any{
		data.Site().Url(),
	}
	result8, err := handlebars.StripQuerystring(args7)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result8); err != nil {
		return err
	}
	if _, err := io.WriteString(w, ")\nFlags ("); err != nil {
		return err
	}
	args9 := []any{
		data.Settings().FeatureFlags(),
	}
	result10, err := handlebars.Size(args9)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result10); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "): "); err != nil {
		return err
	}
	args11 := []any{
		data.Settings().FeatureFlags(),
	}
	result12, err := handlebars.Keys(args11)
	if err != nil {
		return err
	}
	hash13 := runtime.Hash{
		"separator": ", ",
	}
	args14 := []any{
		result12,
		hash13,
	}
	result15, err := handlebars.Join(args14)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result15); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\nFlag values: "); err != nil {
		return err
	}
	args16 := []any{
		data.Settings().FeatureFlags(),
	}
	result17, err := handlebars.Values(args16)
	if err != nil {
		return err
	}
	hash18 := runtime.Hash{
		"separator": ", ",
	}
	args19 := []any{
		result17,
		hash18,
	}
	result20, err := handlebars.Join(args19)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result20); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n"); err != nil {
		return err
	}
	ctx21 := data.User()
	if runtime.IsTruthy(ctx21) {
		if _, err := io.WriteString(w, "\nName: "); err != nil {
			return err
		}
		args22 := []any{
			ctx21.Name(),
		}
		result23, err := handlebars.Capitalize(args22)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result23); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nEmail: "); err != nil {
			return err
		}
		args24 := []any{
			ctx21.Email(),
		}
		result25, err := handlebars.Lower(args24)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result25); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nRole: "); err != nil {
			return err
		}
		args26 := []any{
			ctx21.Role(),
		}
		result27, err := handlebars.Upper(args26)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result27); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nJoined: "); err != nil {
			return err
		}
		hash28 := runtime.Hash{
			"format": "2006-01-02",
		}
		args29 := []any{
			ctx21.Joined(),
			hash28,
		}
		result30, err := handlebars.FormatDate(args29)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result30); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nBio: "); err != nil {
			return err
		}
		hash31 := runtime.Hash{
			"length": int64(60),
			"suffix": "...",
		}
		args32 := []any{
			ctx21.Bio(),
			hash31,
		}
		result33, err := handlebars.Truncate(args32)
		if err != nil {
			return err
		}
		if err := runtime.WriteRaw(w, result33); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nStatus: "); err != nil {
			return err
		}
		args34 := []any{
			nil,
			int64(80),
		}
		result35, err := handlebars.Gt(args34)
		if err != nil {
			return err
		}
		args36 := []any{
			nil,
			result35,
		}
		result37, err := handlebars.And(args36)
		if err != nil {
			return err
		}
		val38 := result37
		cond39 := runtime.IsTruthy(val38)
		if cond39 {
			if _, err := io.WriteString(w, "VIP"); err != nil {
				return err
			}
		} else {
			if _, err := io.WriteString(w, "Standard"); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, "\nTags: "); err != nil {
			return err
		}
		hash40 := runtime.Hash{
			"separator": ", ",
		}
		args41 := []any{
			ctx21.Tags(),
			hash40,
		}
		result42, err := handlebars.Join(args41)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result42); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nProfile: "); err != nil {
			return err
		}
		args43 := []any{
			ctx21.Profile().Title(),
			"n/a",
		}
		result44, err := handlebars.Default(args43)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result44); err != nil {
			return err
		}
		if _, err := io.WriteString(w, " / "); err != nil {
			return err
		}
		args45 := []any{
			ctx21.Profile().Note(),
			"n/a",
		}
		result46, err := handlebars.Default(args45)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result46); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nEmail parts: "); err != nil {
			return err
		}
		args47 := []any{
			ctx21.Email(),
			"@",
		}
		result48, err := handlebars.Split(args47)
		if err != nil {
			return err
		}
		hash49 := runtime.Hash{
			"separator": "@",
		}
		args50 := []any{
			result48,
			hash49,
		}
		result51, err := handlebars.Join(args50)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result51); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\n"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n\nOrders:\n"); err != nil {
		return err
	}
	items54 := data.Orders()
	m55, _eachOk := items54.(map[string]any)
	if _eachOk && len(m55) > 0 {
		for key53, item52 := range m55 {
			_, _ = key53, item52
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
			partialCtx56 := item52
			if err := partials["orderRow"](partialCtx56, w); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nOrder index "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, key53); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " first="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " last="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nParent site: "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nRoot year: "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
		}
	}
	if _, err := io.WriteString(w, "\n\nRaw HTML stripped: "); err != nil {
		return err
	}
	args57 := []any{
		data.RawHtml(),
	}
	result58, err := handlebars.StripTags(args57)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result58); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\nDynamic card:\n"); err != nil {
		return err
	}
	partialCtx59 := data.User()
	args60 := []any{
		data,
		"cardPartial",
	}
	result61, err := handlebars.Lookup(args60)
	if err != nil {
		return err
	}
	partial62 := runtime.Stringify(result61)
	partialFn, ok := partials[partial62]
	if !ok {
		return runtime.MissingPartial(partial62)
	}
	if err := partialFn(partialCtx59, w); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n"); err != nil {
		return err
	}
	if err := renderFooter(data, w); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderMain(w io.Writer, data MainContext) error {
	return renderMain(data, w)
}

func RenderMainString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderMain(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

func renderOrderRow(data OrderRowContext, w io.Writer) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<div class=\"order\">\n  <span>Order #"); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Id()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Items: "); err != nil {
		return err
	}
	args1 := []any{
		data.Items(),
	}
	result2, err := handlebars.Length(args1)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result2); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Subtotal: "); err != nil {
		return err
	}
	hash3 := runtime.Hash{
		"precision": int64(2),
	}
	args4 := []any{
		data.Subtotal(),
		hash3,
	}
	result5, err := handlebars.FormatNumber(args4)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result5); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Tax: "); err != nil {
		return err
	}
	hash6 := runtime.Hash{
		"precision": int64(2),
	}
	args7 := []any{
		data.Tax(),
		hash6,
	}
	result8, err := handlebars.FormatNumber(args7)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result8); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Total: "); err != nil {
		return err
	}
	args9 := []any{
		data.Subtotal(),
		data.Tax(),
	}
	result10, err := handlebars.Add(args9)
	if err != nil {
		return err
	}
	hash11 := runtime.Hash{
		"precision": int64(2),
	}
	args12 := []any{
		result10,
		hash11,
	}
	result13, err := handlebars.FormatNumber(args12)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result13); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>First: "); err != nil {
		return err
	}
	args14 := []any{
		data.Items(),
	}
	result15, err := handlebars.First(args14)
	if err != nil {
		return err
	}
	args16 := []any{
		result15,
		"n/a",
	}
	result17, err := handlebars.Default(args16)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result17); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Last: "); err != nil {
		return err
	}
	args18 := []any{
		data.Items(),
	}
	result19, err := handlebars.Last(args18)
	if err != nil {
		return err
	}
	args20 := []any{
		result19,
		"n/a",
	}
	result21, err := handlebars.Default(args20)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result21); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n</div>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderOrderRow(w io.Writer, data OrderRowContext) error {
	return renderOrderRow(data, w)
}

func RenderOrderRowString(data OrderRowContext) (string, error) {
	var b strings.Builder
	if err := RenderOrderRow(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

func renderUserCard(data UserCardContext, w io.Writer) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<div class=\"user-card\">\n  <h2>"); err != nil {
		return err
	}
	args1 := []any{
		data.Name(),
	}
	result2, err := handlebars.Capitalize(args1)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result2); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</h2>\n  <p>"); err != nil {
		return err
	}
	args3 := []any{
		data.Email(),
	}
	result4, err := handlebars.Lower(args3)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result4); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n  <p>Role: "); err != nil {
		return err
	}
	args5 := []any{
		data.Role(),
	}
	result6, err := handlebars.Upper(args5)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result6); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n  "); err != nil {
		return err
	}
	args7 := []any{
		data.Role(),
		"admin",
	}
	result8, err := handlebars.Eq(args7)
	if err != nil {
		return err
	}
	val9 := result8
	cond10 := runtime.IsTruthy(val9)
	if cond10 {
		if _, err := io.WriteString(w, "<strong>Admin</strong>"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n  "); err != nil {
		return err
	}
	val11 := data.Active()
	cond12 := runtime.IsTruthy(val11)
	if !cond12 {
		if _, err := io.WriteString(w, "<em>Inactive</em>"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n  <p>Score: "); err != nil {
		return err
	}
	args13 := []any{
		data.Score(),
		int64(1),
	}
	result14, err := handlebars.ToFixed(args13)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result14); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n</div>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderUserCard(w io.Writer, data UserCardContext) error {
	return renderUserCard(data, w)
}

func RenderUserCardString(data UserCardContext) (string, error) {
	var b strings.Builder
	if err := RenderUserCard(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}
