// Code generated by hbc; DO NOT EDIT.
// Compiler version: 0.1.2
package showcase

import (
	handlebars "github.com/andriyg76/go-hbars/helpers/handlebars"
	runtime "github.com/andriyg76/go-hbars/runtime"
	"io"
	"strings"
)

// Template inclusion (who includes whom):
// ```mermaid
// flowchart LR
// main --> footer
// main --> header
// ```
//
// Context type structure:
// ```mermaid
// classDiagram
// MainContext --> MainFooterContext : Footer()
// MainContext --> MainHeaderContext : Header()
// class OrderRowContext { }
// class UserCardContext { }
// ```

// from examples/showcase/templates/main.hbs:1

// MainContext is the context interface inferred from template "main".
type MainContext interface {
	Footer() MainFooterContext
	Header() MainHeaderContext
	Orders() any
	RawHtml() any
	Settings() MainSettingsContext
	Site() MainSiteContext
	User() MainUserContext
	Raw() any
}

// MainUserContext is the context for path "user".
type MainUserContext interface {
	Bio() any
	Email() any
	Joined() any
	Name() any
	Profile() MainUserProfileContext
	Role() any
	Tags() any
	Raw() any
}

// MainUserProfileContext is the context for path "user.profile".
type MainUserProfileContext interface {
	Note() any
	Title() any
	Raw() any
}

// MainHeaderContext is the context for path "header".
type MainHeaderContext interface {
	Site() MainHeaderSiteContext
	Raw() any
}

// MainHeaderSiteContext is the context for path "header.site".
type MainHeaderSiteContext interface {
	Title() any
	Url() any
	Raw() any
}

// MainFooterContext is the context for path "footer".
type MainFooterContext interface {
	Stats() MainFooterStatsContext
	Users() any
	Raw() any
}

// MainFooterStatsContext is the context for path "footer.stats".
type MainFooterStatsContext interface {
	Avg() any
	Total() any
	Raw() any
}

// MainSiteContext is the context for path "site".
type MainSiteContext interface {
	Title() any
	Url() any
	Raw() any
}

// MainSettingsContext is the context for path "settings".
type MainSettingsContext interface {
	FeatureFlags() any
	Raw() any
}

// from examples/showcase/templates/orderRow.hbs:1

// OrderRowContext is the context interface inferred from template "orderRow".
type OrderRowContext interface {
	Id() any
	Items() any
	Subtotal() any
	Tax() any
	Raw() any
}

// from examples/showcase/templates/userCard.hbs:1

// UserCardContext is the context interface inferred from template "userCard".
type UserCardContext interface {
	Active() any
	Email() any
	Name() any
	Role() any
	Score() any
	Raw() any
}

// from examples/showcase/templates/main.hbs:1

// MainFooterStatsContextData is a map-backed implementation of MainFooterStatsContext.
type MainFooterStatsContextData struct{ m map[string]any }

func (d MainFooterStatsContextData) Avg() any   { return d.m["avg"] }
func (d MainFooterStatsContextData) Total() any { return d.m["total"] }
func (d MainFooterStatsContextData) Raw() any   { return d.m }

// MainFooterStatsContextFromMap returns a MainFooterStatsContext backed by m. If m is nil, a new empty map is used.
func MainFooterStatsContextFromMap(m map[string]any) MainFooterStatsContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainFooterStatsContextData{m}
}

// MainFooterContextData is a map-backed implementation of MainFooterContext.
type MainFooterContextData struct{ m map[string]any }

func (d MainFooterContextData) Stats() MainFooterStatsContext {
	v := d.m["stats"]
	if v == nil {
		return MainFooterStatsContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainFooterStatsContextData{map[string]any{}}
	}
	return MainFooterStatsContextData{m}
}
func (d MainFooterContextData) Users() any { return d.m["users"] }
func (d MainFooterContextData) Raw() any   { return d.m }

// MainFooterContextFromMap returns a MainFooterContext backed by m. If m is nil, a new empty map is used.
func MainFooterContextFromMap(m map[string]any) MainFooterContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainFooterContextData{m}
}

// MainHeaderSiteContextData is a map-backed implementation of MainHeaderSiteContext.
type MainHeaderSiteContextData struct{ m map[string]any }

func (d MainHeaderSiteContextData) Title() any { return d.m["title"] }
func (d MainHeaderSiteContextData) Url() any   { return d.m["url"] }
func (d MainHeaderSiteContextData) Raw() any   { return d.m }

// MainHeaderSiteContextFromMap returns a MainHeaderSiteContext backed by m. If m is nil, a new empty map is used.
func MainHeaderSiteContextFromMap(m map[string]any) MainHeaderSiteContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainHeaderSiteContextData{m}
}

// MainHeaderContextData is a map-backed implementation of MainHeaderContext.
type MainHeaderContextData struct{ m map[string]any }

func (d MainHeaderContextData) Site() MainHeaderSiteContext {
	v := d.m["site"]
	if v == nil {
		return MainHeaderSiteContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainHeaderSiteContextData{map[string]any{}}
	}
	return MainHeaderSiteContextData{m}
}
func (d MainHeaderContextData) Raw() any { return d.m }

// MainHeaderContextFromMap returns a MainHeaderContext backed by m. If m is nil, a new empty map is used.
func MainHeaderContextFromMap(m map[string]any) MainHeaderContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainHeaderContextData{m}
}

// MainSettingsContextData is a map-backed implementation of MainSettingsContext.
type MainSettingsContextData struct{ m map[string]any }

func (d MainSettingsContextData) FeatureFlags() any { return d.m["featureFlags"] }
func (d MainSettingsContextData) Raw() any          { return d.m }

// MainSettingsContextFromMap returns a MainSettingsContext backed by m. If m is nil, a new empty map is used.
func MainSettingsContextFromMap(m map[string]any) MainSettingsContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainSettingsContextData{m}
}

// MainSiteContextData is a map-backed implementation of MainSiteContext.
type MainSiteContextData struct{ m map[string]any }

func (d MainSiteContextData) Title() any { return d.m["title"] }
func (d MainSiteContextData) Url() any   { return d.m["url"] }
func (d MainSiteContextData) Raw() any   { return d.m }

// MainSiteContextFromMap returns a MainSiteContext backed by m. If m is nil, a new empty map is used.
func MainSiteContextFromMap(m map[string]any) MainSiteContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainSiteContextData{m}
}

// MainUserProfileContextData is a map-backed implementation of MainUserProfileContext.
type MainUserProfileContextData struct{ m map[string]any }

func (d MainUserProfileContextData) Note() any  { return d.m["note"] }
func (d MainUserProfileContextData) Title() any { return d.m["title"] }
func (d MainUserProfileContextData) Raw() any   { return d.m }

// MainUserProfileContextFromMap returns a MainUserProfileContext backed by m. If m is nil, a new empty map is used.
func MainUserProfileContextFromMap(m map[string]any) MainUserProfileContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainUserProfileContextData{m}
}

// MainUserContextData is a map-backed implementation of MainUserContext.
type MainUserContextData struct{ m map[string]any }

func (d MainUserContextData) Bio() any    { return d.m["bio"] }
func (d MainUserContextData) Email() any  { return d.m["email"] }
func (d MainUserContextData) Joined() any { return d.m["joined"] }
func (d MainUserContextData) Name() any   { return d.m["name"] }
func (d MainUserContextData) Profile() MainUserProfileContext {
	v := d.m["profile"]
	if v == nil {
		return MainUserProfileContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainUserProfileContextData{map[string]any{}}
	}
	return MainUserProfileContextData{m}
}
func (d MainUserContextData) Role() any { return d.m["role"] }
func (d MainUserContextData) Tags() any { return d.m["tags"] }
func (d MainUserContextData) Raw() any  { return d.m }

// MainUserContextFromMap returns a MainUserContext backed by m. If m is nil, a new empty map is used.
func MainUserContextFromMap(m map[string]any) MainUserContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainUserContextData{m}
}

// MainContextData is a map-backed implementation of MainContext.
type MainContextData struct{ m map[string]any }

func (d MainContextData) Footer() MainFooterContext {
	v := d.m["footer"]
	if v == nil {
		return MainFooterContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainFooterContextData{map[string]any{}}
	}
	return MainFooterContextData{m}
}
func (d MainContextData) Header() MainHeaderContext {
	v := d.m["header"]
	if v == nil {
		return MainHeaderContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainHeaderContextData{map[string]any{}}
	}
	return MainHeaderContextData{m}
}
func (d MainContextData) Orders() any  { return d.m["orders"] }
func (d MainContextData) RawHtml() any { return d.m["rawHtml"] }
func (d MainContextData) Settings() MainSettingsContext {
	v := d.m["settings"]
	if v == nil {
		return MainSettingsContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainSettingsContextData{map[string]any{}}
	}
	return MainSettingsContextData{m}
}
func (d MainContextData) Site() MainSiteContext {
	v := d.m["site"]
	if v == nil {
		return MainSiteContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainSiteContextData{map[string]any{}}
	}
	return MainSiteContextData{m}
}
func (d MainContextData) User() MainUserContext {
	v := d.m["user"]
	if v == nil {
		return MainUserContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainUserContextData{map[string]any{}}
	}
	return MainUserContextData{m}
}
func (d MainContextData) Raw() any { return d.m }

// MainContextFromMap returns a MainContext backed by m. If m is nil, a new empty map is used.
func MainContextFromMap(m map[string]any) MainContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainContextData{m}
}

// from examples/showcase/templates/orderRow.hbs:1

// OrderRowContextData is a map-backed implementation of OrderRowContext.
type OrderRowContextData struct{ m map[string]any }

func (d OrderRowContextData) Id() any       { return d.m["id"] }
func (d OrderRowContextData) Items() any    { return d.m["items"] }
func (d OrderRowContextData) Subtotal() any { return d.m["subtotal"] }
func (d OrderRowContextData) Tax() any      { return d.m["tax"] }
func (d OrderRowContextData) Raw() any      { return d.m }

// OrderRowContextFromMap returns a OrderRowContext backed by m. If m is nil, a new empty map is used.
func OrderRowContextFromMap(m map[string]any) OrderRowContext {
	if m == nil {
		m = make(map[string]any)
	}
	return OrderRowContextData{m}
}

// from examples/showcase/templates/userCard.hbs:1

// UserCardContextData is a map-backed implementation of UserCardContext.
type UserCardContextData struct{ m map[string]any }

func (d UserCardContextData) Active() any { return d.m["active"] }
func (d UserCardContextData) Email() any  { return d.m["email"] }
func (d UserCardContextData) Name() any   { return d.m["name"] }
func (d UserCardContextData) Role() any   { return d.m["role"] }
func (d UserCardContextData) Score() any  { return d.m["score"] }
func (d UserCardContextData) Raw() any    { return d.m }

// UserCardContextFromMap returns a UserCardContext backed by m. If m is nil, a new empty map is used.
func UserCardContextFromMap(m map[string]any) UserCardContext {
	if m == nil {
		m = make(map[string]any)
	}
	return UserCardContextData{m}
}

var partials map[string]func(any, io.Writer, any) error

// contextMap returns map[string]any from ctx (either direct map or Raw() from context data).
func contextMap(ctx any) map[string]any {
	if m, ok := ctx.(map[string]any); ok {
		return m
	}
	type rawer interface{ Raw() any }
	if r, ok := ctx.(rawer); ok {
		if m, ok := r.Raw().(map[string]any); ok {
			return m
		}
	}
	return nil
}

func init() {
	partials = map[string]func(any, io.Writer, any) error{
		"footer": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderFooter(MainContextFromMap(m), w, MainContextFromMap(m))
		},
		"header": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderHeader(MainContextFromMap(m), w, MainContextFromMap(m))
		},
		"main": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderMain(MainContextFromMap(m), w, MainContextFromMap(m))
		},
		"orderRow": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderOrderRow(OrderRowContextFromMap(m), w, OrderRowContextFromMap(m))
		},
		"userCard": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderUserCard(UserCardContextFromMap(m), w, UserCardContextFromMap(m))
		},
	}
}

// from examples/showcase/templates/footer.hbs:1
func renderFooter(data MainContext, w io.Writer, root MainContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<footer>\n  Total: "); err != nil {
		return err
	}
	args1 := []any{
		nil,
	}
	helperArgs2 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args1,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result3, err := handlebars.FormatNumber(helperArgs2)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result3); err != nil {
		return err
	}
	if _, err := io.WriteString(w, " (avg "); err != nil {
		return err
	}
	args4 := []any{
		nil,
	}
	hash5 := runtime.Hash{
		"precision": int64(2),
	}
	helperArgs6 := runtime.HelperArgs{
		HashArgs:  hash5,
		Args:      args4,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result7, err := handlebars.FormatNumber(helperArgs6)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result7); err != nil {
		return err
	}
	if _, err := io.WriteString(w, ")\n  Users: "); err != nil {
		return err
	}
	args8 := []any{
		nil,
	}
	helperArgs9 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args8,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result10, err := handlebars.Length(helperArgs9)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result10); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n</footer>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderFooter(w io.Writer, data MainContext) error {
	return renderFooter(data, w, data)
}

func RenderFooterString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderFooter(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// from examples/showcase/templates/header.hbs:1
func renderHeader(data MainContext, w io.Writer, root MainContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<header>\n  <h1>"); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Site().Title()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</h1>\n  <p>"); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Site().Url()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n  <p>Generated: "); err != nil {
		return err
	}
	hash1 := runtime.Hash{
		"format": "2006-01-02T15:04:05Z07:00",
	}
	helperArgs2 := runtime.HelperArgs{
		HashArgs:  hash1,
		Args:      nil,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result3, err := handlebars.Now(helperArgs2)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result3); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n</header>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderHeader(w io.Writer, data MainContext) error {
	return renderHeader(data, w, data)
}

func RenderHeaderString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderHeader(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// from examples/showcase/templates/main.hbs:1
func renderMain(data MainContext, w io.Writer, root MainContext) error {
	if data == nil {
		return nil
	}
	if err := renderHeader(data, w, data); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\nSite: "); err != nil {
		return err
	}
	args1 := []any{
		data.Site().Title(),
	}
	helperArgs2 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args1,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result3, err := handlebars.Upper(helperArgs2)
	if err != nil {
		return err
	}
	args4 := []any{
		result3,
		" ",
		"-",
	}
	helperArgs5 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args4,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result6, err := handlebars.Replace(helperArgs5)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result6); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\nURL: "); err != nil {
		return err
	}
	args7 := []any{
		data.Site().Url(),
	}
	helperArgs8 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args7,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result9, err := handlebars.StripProtocol(helperArgs8)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result9); err != nil {
		return err
	}
	if _, err := io.WriteString(w, " (clean: "); err != nil {
		return err
	}
	args10 := []any{
		data.Site().Url(),
	}
	helperArgs11 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args10,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result12, err := handlebars.StripQuerystring(helperArgs11)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result12); err != nil {
		return err
	}
	if _, err := io.WriteString(w, ")\nFlags ("); err != nil {
		return err
	}
	args13 := []any{
		data.Settings().FeatureFlags(),
	}
	helperArgs14 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args13,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result15, err := handlebars.Size(helperArgs14)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result15); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "): "); err != nil {
		return err
	}
	args16 := []any{
		data.Settings().FeatureFlags(),
	}
	helperArgs17 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args16,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result18, err := handlebars.Keys(helperArgs17)
	if err != nil {
		return err
	}
	args19 := []any{
		result18,
	}
	hash20 := runtime.Hash{
		"separator": ", ",
	}
	helperArgs21 := runtime.HelperArgs{
		HashArgs:  hash20,
		Args:      args19,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result22, err := handlebars.Join(helperArgs21)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result22); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\nFlag values: "); err != nil {
		return err
	}
	args23 := []any{
		data.Settings().FeatureFlags(),
	}
	helperArgs24 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args23,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result25, err := handlebars.Values(helperArgs24)
	if err != nil {
		return err
	}
	args26 := []any{
		result25,
	}
	hash27 := runtime.Hash{
		"separator": ", ",
	}
	helperArgs28 := runtime.HelperArgs{
		HashArgs:  hash27,
		Args:      args26,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result29, err := handlebars.Join(helperArgs28)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result29); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n"); err != nil {
		return err
	}
	ctx30 := data.User()
	cond31, err32 := runtime.IsTruthy(ctx30)
	if err32 != nil {
		return err32
	}
	if cond31 {
		if _, err := io.WriteString(w, "\nName: "); err != nil {
			return err
		}
		args33 := []any{
			ctx30.Name(),
		}
		helperArgs34 := runtime.HelperArgs{
			HashArgs:  nil,
			Args:      args33,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result35, err := handlebars.Capitalize(helperArgs34)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result35); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nEmail: "); err != nil {
			return err
		}
		args36 := []any{
			ctx30.Email(),
		}
		helperArgs37 := runtime.HelperArgs{
			HashArgs:  nil,
			Args:      args36,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result38, err := handlebars.Lower(helperArgs37)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result38); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nRole: "); err != nil {
			return err
		}
		args39 := []any{
			ctx30.Role(),
		}
		helperArgs40 := runtime.HelperArgs{
			HashArgs:  nil,
			Args:      args39,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result41, err := handlebars.Upper(helperArgs40)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result41); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nJoined: "); err != nil {
			return err
		}
		args42 := []any{
			ctx30.Joined(),
		}
		hash43 := runtime.Hash{
			"format": "2006-01-02",
		}
		helperArgs44 := runtime.HelperArgs{
			HashArgs:  hash43,
			Args:      args42,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result45, err := handlebars.FormatDate(helperArgs44)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result45); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nBio: "); err != nil {
			return err
		}
		args46 := []any{
			ctx30.Bio(),
		}
		hash47 := runtime.Hash{
			"length": int64(60),
			"suffix": "...",
		}
		helperArgs48 := runtime.HelperArgs{
			HashArgs:  hash47,
			Args:      args46,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result49, err := handlebars.Truncate(helperArgs48)
		if err != nil {
			return err
		}
		if err := runtime.WriteRaw(w, result49); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nStatus: "); err != nil {
			return err
		}
		args50 := []any{
			nil,
			int64(80),
		}
		helperArgs51 := runtime.HelperArgs{
			HashArgs:  nil,
			Args:      args50,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result52, err := handlebars.Gt(helperArgs51)
		if err != nil {
			return err
		}
		args53 := []any{
			nil,
			result52,
		}
		helperArgs54 := runtime.HelperArgs{
			HashArgs:  nil,
			Args:      args53,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result55, err := handlebars.And(helperArgs54)
		if err != nil {
			return err
		}
		val56 := result55
		cond57, err58 := runtime.IsTruthy(val56)
		if err58 != nil {
			return err58
		}
		if cond57 {
			if _, err := io.WriteString(w, "VIP"); err != nil {
				return err
			}
		} else {
			if _, err := io.WriteString(w, "Standard"); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, "\nTags: "); err != nil {
			return err
		}
		args59 := []any{
			ctx30.Tags(),
		}
		hash60 := runtime.Hash{
			"separator": ", ",
		}
		helperArgs61 := runtime.HelperArgs{
			HashArgs:  hash60,
			Args:      args59,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result62, err := handlebars.Join(helperArgs61)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result62); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nProfile: "); err != nil {
			return err
		}
		args63 := []any{
			ctx30.Profile().Title(),
			"n/a",
		}
		helperArgs64 := runtime.HelperArgs{
			HashArgs:  nil,
			Args:      args63,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result65, err := handlebars.Default(helperArgs64)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result65); err != nil {
			return err
		}
		if _, err := io.WriteString(w, " / "); err != nil {
			return err
		}
		args66 := []any{
			ctx30.Profile().Note(),
			"n/a",
		}
		helperArgs67 := runtime.HelperArgs{
			HashArgs:  nil,
			Args:      args66,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result68, err := handlebars.Default(helperArgs67)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result68); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nEmail parts: "); err != nil {
			return err
		}
		args69 := []any{
			ctx30.Email(),
			"@",
		}
		helperArgs70 := runtime.HelperArgs{
			HashArgs:  nil,
			Args:      args69,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result71, err := handlebars.Split(helperArgs70)
		if err != nil {
			return err
		}
		args72 := []any{
			result71,
		}
		hash73 := runtime.Hash{
			"separator": "@",
		}
		helperArgs74 := runtime.HelperArgs{
			HashArgs:  hash73,
			Args:      args72,
			BlockFn:   nil,
			InverseFn: nil,
			IsBlock:   false,
		}
		result75, err := handlebars.Join(helperArgs74)
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result75); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\n"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n\nOrders:\n"); err != nil {
		return err
	}
	items78 := data.Orders()
	sl79, _eachSliceOk := items78.([]any)
	if _eachSliceOk && len(sl79) > 0 {
		for key77, item76 := range sl79 {
			_, _ = key77, item76
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
			partialBase81 := item76
			if err := partials["orderRow"](partialBase81, w, partialBase81); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nOrder index "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, key77); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " first="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " last="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nParent site: "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, data.Site().Title()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nRoot year: "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, runtime.LookupPath(root, "site.year")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
		}
	} else if m80, _eachMapOk := items78.(map[string]any); _eachMapOk && len(m80) > 0 {
		for key77, item76 := range m80 {
			_, _ = key77, item76
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
			partialBase82 := item76
			if err := partials["orderRow"](partialBase82, w, partialBase82); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nOrder index "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, key77); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " first="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " last="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, nil); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nParent site: "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, data.Site().Title()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\nRoot year: "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, runtime.LookupPath(root, "site.year")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
		}
	}
	if _, err := io.WriteString(w, "\n\nRaw HTML stripped: "); err != nil {
		return err
	}
	args83 := []any{
		data.RawHtml(),
	}
	helperArgs84 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args83,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result85, err := handlebars.StripTags(helperArgs84)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result85); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\nDynamic card:\n"); err != nil {
		return err
	}
	partialBase86 := data.User()
	args87 := []any{
		data,
		"cardPartial",
	}
	helperArgs88 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args87,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result89, err := handlebars.Lookup(helperArgs88)
	if err != nil {
		return err
	}
	partial90 := runtime.Stringify(result89)
	partialFn, ok := partials[partial90]
	if !ok {
		runtime.MissingPartialOutput(w, partial90)
	} else if err := partialFn(partialBase86, w, partialBase86); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n"); err != nil {
		return err
	}
	if err := renderFooter(data, w, data); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderMain(w io.Writer, data MainContext) error {
	return renderMain(data, w, data)
}

func RenderMainString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderMain(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// from examples/showcase/templates/orderRow.hbs:1
func renderOrderRow(data OrderRowContext, w io.Writer, root OrderRowContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<div class=\"order\">\n  <span>Order #"); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Id()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Items: "); err != nil {
		return err
	}
	args1 := []any{
		data.Items(),
	}
	helperArgs2 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args1,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result3, err := handlebars.Length(helperArgs2)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result3); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Subtotal: "); err != nil {
		return err
	}
	args4 := []any{
		data.Subtotal(),
	}
	hash5 := runtime.Hash{
		"precision": int64(2),
	}
	helperArgs6 := runtime.HelperArgs{
		HashArgs:  hash5,
		Args:      args4,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result7, err := handlebars.FormatNumber(helperArgs6)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result7); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Tax: "); err != nil {
		return err
	}
	args8 := []any{
		data.Tax(),
	}
	hash9 := runtime.Hash{
		"precision": int64(2),
	}
	helperArgs10 := runtime.HelperArgs{
		HashArgs:  hash9,
		Args:      args8,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result11, err := handlebars.FormatNumber(helperArgs10)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result11); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Total: "); err != nil {
		return err
	}
	args12 := []any{
		data.Subtotal(),
		data.Tax(),
	}
	helperArgs13 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args12,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result14, err := handlebars.Add(helperArgs13)
	if err != nil {
		return err
	}
	args15 := []any{
		result14,
	}
	hash16 := runtime.Hash{
		"precision": int64(2),
	}
	helperArgs17 := runtime.HelperArgs{
		HashArgs:  hash16,
		Args:      args15,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result18, err := handlebars.FormatNumber(helperArgs17)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result18); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>First: "); err != nil {
		return err
	}
	args19 := []any{
		data.Items(),
	}
	helperArgs20 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args19,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result21, err := handlebars.First(helperArgs20)
	if err != nil {
		return err
	}
	args22 := []any{
		result21,
		"n/a",
	}
	helperArgs23 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args22,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result24, err := handlebars.Default(helperArgs23)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result24); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n  <span>Last: "); err != nil {
		return err
	}
	args25 := []any{
		data.Items(),
	}
	helperArgs26 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args25,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result27, err := handlebars.Last(helperArgs26)
	if err != nil {
		return err
	}
	args28 := []any{
		result27,
		"n/a",
	}
	helperArgs29 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args28,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result30, err := handlebars.Default(helperArgs29)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result30); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</span>\n</div>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderOrderRow(w io.Writer, data OrderRowContext) error {
	return renderOrderRow(data, w, data)
}

func RenderOrderRowString(data OrderRowContext) (string, error) {
	var b strings.Builder
	if err := RenderOrderRow(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// from examples/showcase/templates/userCard.hbs:1
func renderUserCard(data UserCardContext, w io.Writer, root UserCardContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "<div class=\"user-card\">\n  <h2>"); err != nil {
		return err
	}
	args1 := []any{
		data.Name(),
	}
	helperArgs2 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args1,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result3, err := handlebars.Capitalize(helperArgs2)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result3); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</h2>\n  <p>"); err != nil {
		return err
	}
	args4 := []any{
		data.Email(),
	}
	helperArgs5 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args4,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result6, err := handlebars.Lower(helperArgs5)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result6); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n  <p>Role: "); err != nil {
		return err
	}
	args7 := []any{
		data.Role(),
	}
	helperArgs8 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args7,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result9, err := handlebars.Upper(helperArgs8)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result9); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n  "); err != nil {
		return err
	}
	args10 := []any{
		data.Role(),
		"admin",
	}
	helperArgs11 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args10,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result12, err := handlebars.Eq(helperArgs11)
	if err != nil {
		return err
	}
	val13 := result12
	cond14, err15 := runtime.IsTruthy(val13)
	if err15 != nil {
		return err15
	}
	if cond14 {
		if _, err := io.WriteString(w, "<strong>Admin</strong>"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n  "); err != nil {
		return err
	}
	val16 := data.Active()
	cond17, err18 := runtime.IsTruthy(val16)
	if err18 != nil {
		return err18
	}
	if !cond17 {
		if _, err := io.WriteString(w, "<em>Inactive</em>"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n  <p>Score: "); err != nil {
		return err
	}
	args19 := []any{
		data.Score(),
		int64(1),
	}
	helperArgs20 := runtime.HelperArgs{
		HashArgs:  nil,
		Args:      args19,
		BlockFn:   nil,
		InverseFn: nil,
		IsBlock:   false,
	}
	result21, err := handlebars.ToFixed(helperArgs20)
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result21); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "</p>\n</div>\n\n\n\n"); err != nil {
		return err
	}
	return nil
}

func RenderUserCard(w io.Writer, data UserCardContext) error {
	return renderUserCard(data, w, data)
}

func RenderUserCardString(data UserCardContext) (string, error) {
	var b strings.Builder
	if err := RenderUserCard(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}
