// Code generated by hbc; DO NOT EDIT.
// Compiler version: 0.1.2
package compat

import (
	handlebars "github.com/andriyg76/go-hbars/helpers/handlebars"
	runtime "github.com/andriyg76/go-hbars/runtime"
	"io"
	"strings"
)

// Template inclusion (who includes whom):
// ```mermaid
// flowchart LR
// main --> footer
// ```
//
// Context type structure:
// ```mermaid
// classDiagram
// MainContext --> MainFooterContext : Footer()
// class UserCardContext { }
// ```

// from examples/compat/templates/main.hbs:1

// MainContext is the context interface inferred from template "main".
type MainContext interface {
	Footer() MainFooterContext
	Idx() any
	Note() any
	Settings() any
	Title() any
	User() MainUserContext
	Users() []MainUsersItemContext
	Raw() any
}

// MainFooterContext is the context for path "footer".
type MainFooterContext interface {
	Note() any
	Raw() any
}

// MainUserContext is the context for path "user".
type MainUserContext interface {
	Created() any
	Name() any
	Nickname() any
	Role() any
	Raw() any
}

// MainUsersItemContext is the context for one element of users.
type MainUsersItemContext interface {
	Active() any
	Name() any
	Raw() any
}

// from examples/compat/templates/userCard.hbs:1

// UserCardContext is the context interface inferred from template "userCard".
type UserCardContext interface {
	Name() any
	Role() any
	Raw() any
}

// from examples/compat/templates/main.hbs:1

// MainFooterContextData is a map-backed implementation of MainFooterContext.
type MainFooterContextData struct{ m map[string]any }

func (d MainFooterContextData) Note() any { return d.m["note"] }
func (d MainFooterContextData) Raw() any  { return d.m }

// MainFooterContextFromMap returns a MainFooterContext backed by m. If m is nil, a new empty map is used.
func MainFooterContextFromMap(m map[string]any) MainFooterContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainFooterContextData{m}
}

// MainUserContextData is a map-backed implementation of MainUserContext.
type MainUserContextData struct{ m map[string]any }

func (d MainUserContextData) Created() any  { return d.m["created"] }
func (d MainUserContextData) Name() any     { return d.m["name"] }
func (d MainUserContextData) Nickname() any { return d.m["nickname"] }
func (d MainUserContextData) Role() any     { return d.m["role"] }
func (d MainUserContextData) Raw() any      { return d.m }

// MainUserContextFromMap returns a MainUserContext backed by m. If m is nil, a new empty map is used.
func MainUserContextFromMap(m map[string]any) MainUserContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainUserContextData{m}
}

// MainUsersItemContextData is a map-backed implementation of MainUsersItemContext.
type MainUsersItemContextData struct{ m map[string]any }

func (d MainUsersItemContextData) Active() any { return d.m["active"] }
func (d MainUsersItemContextData) Name() any   { return d.m["name"] }
func (d MainUsersItemContextData) Raw() any    { return d.m }

// MainUsersItemContextFromMap returns a MainUsersItemContext backed by m. If m is nil, a new empty map is used.
func MainUsersItemContextFromMap(m map[string]any) MainUsersItemContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainUsersItemContextData{m}
}

// MainContextData is a map-backed implementation of MainContext.
type MainContextData struct{ m map[string]any }

func (d MainContextData) Footer() MainFooterContext {
	v := d.m["footer"]
	if v == nil {
		return MainFooterContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainFooterContextData{map[string]any{}}
	}
	return MainFooterContextData{m}
}
func (d MainContextData) Idx() any      { return d.m["idx"] }
func (d MainContextData) Note() any     { return d.m["note"] }
func (d MainContextData) Settings() any { return d.m["settings"] }
func (d MainContextData) Title() any    { return d.m["title"] }
func (d MainContextData) User() MainUserContext {
	v := d.m["user"]
	if v == nil {
		return MainUserContextData{map[string]any{}}
	}
	m, ok := v.(map[string]any)
	if !ok {
		return MainUserContextData{map[string]any{}}
	}
	return MainUserContextData{m}
}
func (d MainContextData) Users() []MainUsersItemContext {
	v := d.m["users"]
	if v == nil {
		return nil
	}
	s, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]MainUsersItemContext, len(s))
	for i := range s {
		if m, ok := s[i].(map[string]any); ok {
			out[i] = MainUsersItemContextData{m}
		}
	}
	return out
}
func (d MainContextData) Raw() any { return d.m }

// MainContextFromMap returns a MainContext backed by m. If m is nil, a new empty map is used.
func MainContextFromMap(m map[string]any) MainContext {
	if m == nil {
		m = make(map[string]any)
	}
	return MainContextData{m}
}

// from examples/compat/templates/userCard.hbs:1

// UserCardContextData is a map-backed implementation of UserCardContext.
type UserCardContextData struct{ m map[string]any }

func (d UserCardContextData) Name() any { return d.m["name"] }
func (d UserCardContextData) Role() any { return d.m["role"] }
func (d UserCardContextData) Raw() any  { return d.m }

// UserCardContextFromMap returns a UserCardContext backed by m. If m is nil, a new empty map is used.
func UserCardContextFromMap(m map[string]any) UserCardContext {
	if m == nil {
		m = make(map[string]any)
	}
	return UserCardContextData{m}
}

var partials map[string]func(any, io.Writer, any) error

// contextMap returns map[string]any from ctx (either direct map or Raw() from context data).
func contextMap(ctx any) map[string]any {
	if m, ok := ctx.(map[string]any); ok {
		return m
	}
	type rawer interface{ Raw() any }
	if r, ok := ctx.(rawer); ok {
		if m, ok := r.Raw().(map[string]any); ok {
			return m
		}
	}
	return nil
}

func init() {
	partials = map[string]func(any, io.Writer, any) error{
		"footer": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderFooter(MainContextFromMap(m), w, MainContextFromMap(m))
		},
		"main": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderMain(MainContextFromMap(m), w, MainContextFromMap(m))
		},
		"userCard": func(ctx any, w io.Writer, root any) error {
			m := contextMap(ctx)
			if m == nil {
				return nil
			}
			return renderUserCard(UserCardContextFromMap(m), w, UserCardContextFromMap(m))
		},
	}
}

// from examples/compat/templates/footer.hbs:1
func renderFooter(data MainContext, w io.Writer, root MainContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "Footer: "); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Note()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n"); err != nil {
		return err
	}
	return nil
}

func RenderFooter(w io.Writer, data MainContext) error {
	return renderFooter(data, w, data)
}

func RenderFooterString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderFooter(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// from examples/compat/templates/main.hbs:1
func renderMain(data MainContext, w io.Writer, root MainContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "Title:"); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Title()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\nUpper/Lower: "); err != nil {
		return err
	}
	result1, err := handlebars.Lower(runtime.HelperArgs{
		Args: []any{
			data.Title(),
		},
	})
	if err != nil {
		return err
	}
	result2, err := handlebars.Upper(runtime.HelperArgs{
		Args: []any{
			result1,
		},
	})
	if err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, result2); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n"); err != nil {
		return err
	}
	u := data.User()
	cond4, err5 := runtime.IsTruthy(u)
	if err5 != nil {
		return err5
	}
	if cond4 {
		if _, err := io.WriteString(w, "\nUser: "); err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, u.Name()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, " ("); err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, u.Role()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, ")\nCreated: "); err != nil {
			return err
		}
		result6, err := handlebars.FormatDate(runtime.HelperArgs{
			Args: []any{
				u.Created(),
			},
			HashArgs: runtime.Hash{
				"format": "2006-01-02",
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result6); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\nNickname: "); err != nil {
			return err
		}
		result7, err := handlebars.Default(runtime.HelperArgs{
			Args: []any{
				u.Nickname(),
			},
			HashArgs: runtime.Hash{
				"value": "(none)",
			},
		})
		if err != nil {
			return err
		}
		if err := runtime.WriteEscaped(w, result7); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\n"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n\nUsers:\n"); err != nil {
		return err
	}
	items10 := data.Users()
	if len(items10) > 0 {
		for key9, item8 := range items10 {
			_, _ = key9, item8
			if _, err := io.WriteString(w, "\n  "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, key9); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "/"); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, key9); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, item8.Name()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, " "); err != nil {
				return err
			}
			val11 := item8.Active()
			cond12, err13 := runtime.IsTruthy(val11)
			if err13 != nil {
				return err13
			}
			if cond12 {
				if _, err := io.WriteString(w, "(active)"); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, " - "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, data.Title()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
		}
	} else {
		if _, err := io.WriteString(w, "\n  (none)\n"); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\n\nSettings:\n"); err != nil {
		return err
	}
	items16 := data.Settings()
	sl17, _eachSliceOk := items16.([]any)
	if _eachSliceOk && len(sl17) > 0 {
		for key15, item14 := range sl17 {
			_, _ = key15, item14
			if _, err := io.WriteString(w, "\n  "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, key15); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, item14); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
		}
	} else if m18, _eachMapOk := items16.(map[string]any); _eachMapOk && len(m18) > 0 {
		for key15, item14 := range m18 {
			_, _ = key15, item14
			if _, err := io.WriteString(w, "\n  "); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, key15); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "="); err != nil {
				return err
			}
			if err := runtime.WriteEscaped(w, item14); err != nil {
				return err
			}
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
		}
	}
	if _, err := io.WriteString(w, "\n\n"); err != nil {
		return err
	}
	partialBase19 := data.User()
	result20, err := handlebars.Lookup(runtime.HelperArgs{
		Args: []any{
			data,
			"cardPartial",
		},
	})
	if err != nil {
		return err
	}
	partial21 := runtime.Stringify(result20)
	partialFn, ok := partials[partial21]
	if !ok {
		runtime.MissingPartialOutput(w, partial21)
	} else if err := partialFn(partialBase19, w, partialBase19); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n"); err != nil {
		return err
	}
	partialCtx22 := map[string]any{
		"note": "thanks",
	}
	partialCtx23 := runtime.MergePartialContext(nil, partialCtx22)
	if err := partials["footer"](partialCtx23, w, partialCtx23); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n\n"); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n{{should_not_parse}}\n"); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n"); err != nil {
		return err
	}
	return nil
}

func RenderMain(w io.Writer, data MainContext) error {
	return renderMain(data, w, data)
}

func RenderMainString(data MainContext) (string, error) {
	var b strings.Builder
	if err := RenderMain(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// from examples/compat/templates/userCard.hbs:1
func renderUserCard(data UserCardContext, w io.Writer, root UserCardContext) error {
	if data == nil {
		return nil
	}
	if _, err := io.WriteString(w, "UserCard: "); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Name()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, " ("); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, data.Role()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, ")\nRoot: "); err != nil {
		return err
	}
	if err := runtime.WriteEscaped(w, runtime.LookupPath(root, "title")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n"); err != nil {
		return err
	}
	return nil
}

func RenderUserCard(w io.Writer, data UserCardContext) error {
	return renderUserCard(data, w, data)
}

func RenderUserCardString(data UserCardContext) (string, error) {
	var b strings.Builder
	if err := RenderUserCard(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}
